spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    defer-datasource-initialization: true
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          google:
            clientId: 599197172710-efa0msdp08cvjmaq1nihktmfodum7rdr.apps.googleusercontent.com
            clientSecret: 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
            scope: email, profile
  kafka:
    bootstrap-servers:
#      - kafka.tacocloud.com:9092
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic

logging:
  level:
    root: INFO
taco:
  orders:
    pageSize: 10

