server:
  port: 9090
logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
        provider:
          tacocloud:
            issuer-uri: http://localhost:9000
  kafka:
    bootstrap-servers:
      #      - kafka.tacocloud.com:9092
      - localhost:9092
    template:
      default-topic: tacocloud.orders.topic